method: grid

metric:
  name: diff_max_min_ood
  goal: maximize

parameters:
  batch_size:
    values: [8]
  opt:
    values: ["adam"]
  lr:
    values: [0.0001]
  wd:
    values: [0.01, 0.001, 0]
  rdm_seed: 
    values: [365, 495, 109, 92, 105]
  shuffle_seed: 
    values: [161, 231, 220] 

  # SPECIFIC TO LSTMs
  num_layers:
    values: [2, 3] 
  dropout_rate:
    values: [0.0]
  embedding_dim:
    values: [64]
  hidden_dim:
    values: [128, 256]
  